services:
  - type: web
    name: cubit-platform
    env: docker
    plan: free
    repo: https://github.com/Diklass/cubit-platform
    branch: main
    dockerComposeFilePath: ./docker-compose.yml
    buildFilter:
      paths:
        - ./**
    autoDeploy: true

